import type { DirectoryListing } from '@/types';
import { pinListing } from '@/lib/placePrecision';
import { placeGallery } from '@/lib/placeImagery';

export interface TurkeyAirportSeed {
  iata: string;
  name: string;
  name_en: string;
  city: string;
  cityEn: string;
  address: string;
  lat: number;
  lng: number;
  phone: string;
  hours: string;
  website: string;
  terminals: string;
  transit: string;
}

const AIRPORTS: TurkeyAirportSeed[] = [
  {
    iata: 'IST',
    name: 'مطار إسطنبول — IST',
    name_en: 'Istanbul Airport (IST)',
    city: 'إسطنبول',
    cityEn: 'Istanbul',
    address: 'Tayakadın, Arnavutköy, İstanbul',
    lat: 41.26083,
    lng: 28.74278,
    phone: '+90 444 1442',
    hours: '24/7',
    website: 'https://www.istairport.com',
    terminals: 'مبنى ركاب واحد متعدد الأجنحة (داخلي / دولي) مع صالات CIP ومكاتب خدمة المسافر.',
    transit: 'مترو M11 إلى Gayrettepe، حافلات Havaist إلى تقسيم/السلطان أحمد، تاكسي رسمي وHAVAİST.',
  },
  {
    iata: 'SAW',
    name: 'مطار صبيحة كوكجن — SAW',
    name_en: 'Sabiha Gökçen International Airport (SAW)',
    city: 'إسطنبول',
    cityEn: 'Istanbul',
    address: 'Sanayi Mahallesi, Pendik, İstanbul',
    lat: 40.89861,
    lng: 29.30917,
    phone: '+90 216 588 8000',
    hours: '24/7',
    website: 'https://www.sabihagokcen.aero',
    terminals: 'مبنى ركاب دولي/داخلي مشترك مع توسعة الجناح الشرقي.',
    transit: 'مترو M4 إلى Kadıköy عبر Tavşantepe، حافلات HAVABUS إلى تقسيم وكاديكوي، تاكسي رسمي.',
  },
  {
    iata: 'AYT',
    name: 'مطار أنطاليا — AYT',
    name_en: 'Antalya Airport (AYT)',
    city: 'أنطاليا',
    cityEn: 'Antalya',
    address: 'Yenigöl, Muratpaşa, Antalya',
    lat: 36.89861,
    lng: 30.80056,
    phone: '+90 242 444 0742',
    hours: '24/7',
    website: 'https://www.antalya-airport.aero',
    terminals: 'T1 الدولي، T2 الداخلي، ومبنى الشركات الخاصة.',
    transit: 'حافلات Havas/Antalya Card إلى مركز المدينة، ترام/باص إلى Lara، تاكسي رسمي.',
  },
  {
    iata: 'TZX',
    name: 'مطار طرابزون — TZX',
    name_en: 'Trabzon Airport (TZX)',
    city: 'طرابزون',
    cityEn: 'Trabzon',
    address: 'Çarşıbaşı Yolu, Trabzon',
    lat: 40.99500,
    lng: 39.78972,
    phone: '+90 462 325 8400',
    hours: '24/7',
    website: 'https://www.trabzon.dhmi.gov.tr',
    terminals: 'مبنى ركاب واحد للرحلات الداخلية والدولية.',
    transit: 'حافلات بلدية إلى ميدان Uzun Sokak، HAVAS موسمي، تاكسي رسمي أمام الصالة.',
  },
  {
    iata: 'ESB',
    name: 'مطار إسنبوغا أنقرة — ESB',
    name_en: 'Ankara Esenboğa Airport (ESB)',
    city: 'أنقرة',
    cityEn: 'Ankara',
    address: 'Esenboğa, Çubuk, Ankara',
    lat: 40.12810,
    lng: 32.99510,
    phone: '+90 312 590 4000',
    hours: '24/7',
    website: 'https://www.esenbogaairport.com',
    terminals: 'مبنى داخلي ومبنى دولي متجاوران مع ممرات نقل أرضي.',
    transit: 'حافلات Belde/Havaş إلى AŞTİ وكيزيلاي، تاكسي رسمي، لا مترو مباشر حالياً.',
  },
  {
    iata: 'ADB',
    name: 'مطار عدنان مندريس إزمير — ADB',
    name_en: 'İzmir Adnan Menderes Airport (ADB)',
    city: 'إزمير',
    cityEn: 'Izmir',
    address: 'Dokuz Eylül, Gaziemir, İzmir',
    lat: 38.29240,
    lng: 27.15700,
    phone: '+90 232 455 0000',
    hours: '24/7',
    website: 'https://www.adnanmenderesairport.com',
    terminals: 'مبنى داخلي ومبنى دولي متصلان بقطار İZBAN.',
    transit: 'قطار İZBAN إلى Alsancak، حافلات Havaş إلى كوناك، تاكسي رسمي.',
  },
  {
    iata: 'ADA',
    name: 'مطار أضنة شاكير باشا — ADA',
    name_en: 'Adana Şakirpaşa Airport (ADA)',
    city: 'أضنة',
    cityEn: 'Adana',
    address: 'Şakirpaşa, Seyhan, Adana',
    lat: 36.98222,
    lng: 35.28036,
    phone: '+90 322 435 0311',
    hours: '24/7',
    website: 'https://www.adana.dhmi.gov.tr',
    terminals: 'مبنى ركاب واحد للرحلات الداخلية والدولية.',
    transit: 'حافلات بلدية إلى مركز Seyhan، تاكسي رسمي أمام الصالة.',
  },
  {
    iata: 'GZT',
    name: 'مطار غازي عنتاب — GZT',
    name_en: 'Gaziantep Airport (GZT)',
    city: 'غازي عنتاب',
    cityEn: 'Gaziantep',
    address: 'Oğuzeli, Gaziantep',
    lat: 36.94718,
    lng: 37.47868,
    phone: '+90 342 337 5300',
    hours: '24/7',
    website: 'https://www.gaziantep.dhmi.gov.tr',
    terminals: 'مبنى ركاب حديث للرحلات الداخلية والدولية.',
    transit: 'حافلات Gaziulaş إلى المركز، تاكسي رسمي.',
  },
  {
    iata: 'ASR',
    name: 'مطار قيصري أركيلت — ASR',
    name_en: 'Kayseri Erkilet Airport (ASR)',
    city: 'قيصري',
    cityEn: 'Kayseri',
    address: 'Erkilet, Kocasinan, Kayseri',
    lat: 38.77040,
    lng: 35.49540,
    phone: '+90 352 337 5400',
    hours: '24/7',
    website: 'https://www.kayseri.dhmi.gov.tr',
    terminals: 'مبنى ركاب واحد مع بوابة داخلية ودولية.',
    transit: 'حافلات بلدية إلى ساحة الجمهورية، تاكسي رسمي.',
  },
  {
    iata: 'BJV',
    name: 'مطار بودروم ميلاس — BJV',
    name_en: 'Milas–Bodrum Airport (BJV)',
    city: 'موغلا',
    cityEn: 'Mugla',
    address: 'Ekinanbarı, Milas, Muğla',
    lat: 37.25061,
    lng: 27.66444,
    phone: '+90 252 523 0101',
    hours: '24/7',
    website: 'https://www.milas-bodrumairport.com',
    terminals: 'مبنى داخلي ومبنى دولي منفصلان.',
    transit: 'حافلات Havaş إلى بودروم وميلاس، تاكسي رسمي.',
  },
  {
    iata: 'DLM',
    name: 'مطار دالامان — DLM',
    name_en: 'Dalaman Airport (DLM)',
    city: 'موغلا',
    cityEn: 'Mugla',
    address: 'Dalaman, Muğla',
    lat: 36.71306,
    lng: 28.79250,
    phone: '+90 252 792 5555',
    hours: '24/7',
    website: 'https://www.dalamanairport.com',
    terminals: 'مبنى داخلي ومبنى دولي.',
    transit: 'حافلات إلى فتحية/مرمريس/دalaman، تاكسي رسمي.',
  },
  {
    iata: 'DIY',
    name: 'مطار ديار بكر — DIY',
    name_en: 'Diyarbakır Airport (DIY)',
    city: 'ديار بكر',
    cityEn: 'Diyarbakir',
    address: 'Bağivar, Yenişehir, Diyarbakır',
    lat: 37.89389,
    lng: 40.20102,
    phone: '+90 412 226 1801',
    hours: '24/7',
    website: 'https://www.diyarbakir.dhmi.gov.tr',
    terminals: 'مبنى ركاب واحد.',
    transit: 'حافلات بلدية إلى مركز أوفيك، تاكسي رسمي.',
  },
  {
    iata: 'VAN',
    name: 'مطار فان فریت ملين — VAN',
    name_en: 'Van Ferit Melen Airport (VAN)',
    city: 'وان',
    cityEn: 'Van',
    address: 'Edremit, Van',
    lat: 38.46822,
    lng: 43.33231,
    phone: '+90 432 217 1801',
    hours: '24/7',
    website: 'https://www.van.dhmi.gov.tr',
    terminals: 'مبنى ركاب واحد للرحلات الداخلية.',
    transit: 'حافلات إلى مركز وان، تاكسي رسمي.',
  },
  {
    iata: 'SZF',
    name: 'مطار سامسون تشارشمبا — SZF',
    name_en: 'Samsun Çarşamba Airport (SZF)',
    city: 'سامسون',
    cityEn: 'Samsun',
    address: 'Çarşamba, Samsun',
    lat: 41.25447,
    lng: 36.56710,
    phone: '+90 362 844 8820',
    hours: '24/7',
    website: 'https://www.samsun.dhmi.gov.tr',
    terminals: 'مبنى ركاب واحد.',
    transit: 'حافلات إلى مركز سامسون، تاكسي رسمي.',
  },
];

export function turkeyAirportListings(): DirectoryListing[] {
  return AIRPORTS.map((airport, index) => {
    const listing: DirectoryListing = {
      id: `airport-${airport.iata.toLowerCase()}`,
      category_key: 'airports',
      category_label: 'المطارات',
      name: airport.name,
      description: `${airport.name_en} · ${airport.terminals} ${airport.transit}`,
      country_name: 'تركيا',
      city: airport.city,
      address: airport.address,
      image: '',
      images: [],
      rating: 4.5,
      price_level: '',
      tags: [airport.iata, '24/7', 'صالة ركاب', 'نقل إلى المدينة'],
      proximity_note: airport.transit,
      phone: airport.phone,
      hours: airport.hours,
      is_featured: airport.iata === 'IST' || airport.iata === 'SAW',
      sort_order: index,
      lat: airport.lat,
      lng: airport.lng,
      metro_station_name: '',
      metro_walk_minutes: 0,
      review_count: 0,
      created_at: '',
      nav_query: `${airport.lat.toFixed(7)},${airport.lng.toFixed(7)}`,
      website: airport.website,
    };
    listing.images = placeGallery(listing);
    listing.image = listing.images[0] || '';
    return pinListing(listing);
  }).filter((item): item is DirectoryListing => Boolean(item));
}
