/** ISO 4217 circulating currencies. `perUsd` is official mid-market units per 1 USD (fallback). */

export interface WorldCurrency {
  code: string;
  nameAr: string;
  nameEn: string;
  flag: string;
  perUsd: number;
}

export const WORLD_CURRENCIES: WorldCurrency[] = [
  { code: 'USD', nameAr: 'دولار أمريكي', nameEn: 'US Dollar', flag: '🇺🇸', perUsd: 1 },
  { code: 'EUR', nameAr: 'يورو', nameEn: 'Euro', flag: '🇪🇺', perUsd: 0.86 },
  { code: 'GBP', nameAr: 'جنيه إسترليني', nameEn: 'British Pound', flag: '🇬🇧', perUsd: 0.74 },
  { code: 'IQD', nameAr: 'دينار عراقي', nameEn: 'Iraqi Dinar', flag: '🇮🇶', perUsd: 1310 },
  { code: 'AED', nameAr: 'درهم إماراتي', nameEn: 'UAE Dirham', flag: '🇦🇪', perUsd: 3.6725 },
  { code: 'SAR', nameAr: 'ريال سعودي', nameEn: 'Saudi Riyal', flag: '🇸🇦', perUsd: 3.75 },
  { code: 'KWD', nameAr: 'دينار كويتي', nameEn: 'Kuwaiti Dinar', flag: '🇰🇼', perUsd: 0.307 },
  { code: 'BHD', nameAr: 'دينار بحريني', nameEn: 'Bahraini Dinar', flag: '🇧🇭', perUsd: 0.376 },
  { code: 'OMR', nameAr: 'ريال عماني', nameEn: 'Omani Rial', flag: '🇴🇲', perUsd: 0.3845 },
  { code: 'QAR', nameAr: 'ريال قطري', nameEn: 'Qatari Riyal', flag: '🇶🇦', perUsd: 3.64 },
  { code: 'JOD', nameAr: 'دينار أردني', nameEn: 'Jordanian Dinar', flag: '🇯🇴', perUsd: 0.709 },
  { code: 'EGP', nameAr: 'جنيه مصري', nameEn: 'Egyptian Pound', flag: '🇪🇬', perUsd: 48.4 },
  { code: 'TRY', nameAr: 'ليرة تركية', nameEn: 'Turkish Lira', flag: '🇹🇷', perUsd: 41.2 },
  { code: 'IRR', nameAr: 'ريال إيراني', nameEn: 'Iranian Rial', flag: '🇮🇷', perUsd: 42000 },
  { code: 'SYP', nameAr: 'ليرة سورية', nameEn: 'Syrian Pound', flag: '🇸🇾', perUsd: 13000 },
  { code: 'LBP', nameAr: 'ليرة لبنانية', nameEn: 'Lebanese Pound', flag: '🇱🇧', perUsd: 89500 },
  { code: 'YER', nameAr: 'ريال يمني', nameEn: 'Yemeni Rial', flag: '🇾🇪', perUsd: 250 },
  { code: 'MAD', nameAr: 'درهم مغربي', nameEn: 'Moroccan Dirham', flag: '🇲🇦', perUsd: 9.15 },
  { code: 'TND', nameAr: 'دينار تونسي', nameEn: 'Tunisian Dinar', flag: '🇹🇳', perUsd: 2.92 },
  { code: 'DZD', nameAr: 'دينار جزائري', nameEn: 'Algerian Dinar', flag: '🇩🇿', perUsd: 132 },
  { code: 'LYD', nameAr: 'دينار ليبي', nameEn: 'Libyan Dinar', flag: '🇱🇾', perUsd: 5.45 },
  { code: 'SDG', nameAr: 'جنيه سوداني', nameEn: 'Sudanese Pound', flag: '🇸🇩', perUsd: 600 },
  { code: 'MRU', nameAr: 'أوقية موريتانية', nameEn: 'Mauritanian Ouguiya', flag: '🇲🇷', perUsd: 39.8 },
  { code: 'ILS', nameAr: 'شيكل إسرائيلي', nameEn: 'Israeli Shekel', flag: '🇮🇱', perUsd: 3.33 },
  { code: 'JPY', nameAr: 'ين ياباني', nameEn: 'Japanese Yen', flag: '🇯🇵', perUsd: 147.5 },
  { code: 'CNY', nameAr: 'يوان صيني', nameEn: 'Chinese Yuan', flag: '🇨🇳', perUsd: 7.12 },
  { code: 'HKD', nameAr: 'دولار هونغ كونغ', nameEn: 'Hong Kong Dollar', flag: '🇭🇰', perUsd: 7.78 },
  { code: 'TWD', nameAr: 'دولار تايواني', nameEn: 'New Taiwan Dollar', flag: '🇹🇼', perUsd: 31.8 },
  { code: 'KRW', nameAr: 'وون كوري جنوبي', nameEn: 'South Korean Won', flag: '🇰🇷', perUsd: 1390 },
  { code: 'KPW', nameAr: 'وون كوري شمالي', nameEn: 'North Korean Won', flag: '🇰🇵', perUsd: 900 },
  { code: 'INR', nameAr: 'روبية هندية', nameEn: 'Indian Rupee', flag: '🇮🇳', perUsd: 88.4 },
  { code: 'PKR', nameAr: 'روبية باكستانية', nameEn: 'Pakistani Rupee', flag: '🇵🇰', perUsd: 281 },
  { code: 'BDT', nameAr: 'تاكا بنغلاديشي', nameEn: 'Bangladeshi Taka', flag: '🇧🇩', perUsd: 122 },
  { code: 'LKR', nameAr: 'روبية سريلانكية', nameEn: 'Sri Lankan Rupee', flag: '🇱🇰', perUsd: 302 },
  { code: 'NPR', nameAr: 'روبية نيبالية', nameEn: 'Nepalese Rupee', flag: '🇳🇵', perUsd: 141.4 },
  { code: 'MVR', nameAr: 'روفيا مالديفية', nameEn: 'Maldivian Rufiyaa', flag: '🇲🇻', perUsd: 15.4 },
  { code: 'AFN', nameAr: 'أفغاني', nameEn: 'Afghan Afghani', flag: '🇦🇫', perUsd: 68.5 },
  { code: 'MYR', nameAr: 'رينغيت ماليزي', nameEn: 'Malaysian Ringgit', flag: '🇲🇾', perUsd: 4.22 },
  { code: 'SGD', nameAr: 'دولار سنغافوري', nameEn: 'Singapore Dollar', flag: '🇸🇬', perUsd: 1.29 },
  { code: 'IDR', nameAr: 'روبية إندونيسية', nameEn: 'Indonesian Rupiah', flag: '🇮🇩', perUsd: 16450 },
  { code: 'THB', nameAr: 'بات تايلندي', nameEn: 'Thai Baht', flag: '🇹🇭', perUsd: 32.4 },
  { code: 'VND', nameAr: 'دونغ فيتنامي', nameEn: 'Vietnamese Dong', flag: '🇻🇳', perUsd: 26350 },
  { code: 'PHP', nameAr: 'بيزو فلبيني', nameEn: 'Philippine Peso', flag: '🇵🇭', perUsd: 58.2 },
  { code: 'KHR', nameAr: 'ريال كمبودي', nameEn: 'Cambodian Riel', flag: '🇰🇭', perUsd: 4100 },
  { code: 'LAK', nameAr: 'كيب لاوسي', nameEn: 'Lao Kip', flag: '🇱🇦', perUsd: 21700 },
  { code: 'MMK', nameAr: 'كيات ميانماري', nameEn: 'Myanmar Kyat', flag: '🇲🇲', perUsd: 2100 },
  { code: 'BND', nameAr: 'دولار بروناي', nameEn: 'Brunei Dollar', flag: '🇧🇳', perUsd: 1.29 },
  { code: 'AUD', nameAr: 'دولار أسترالي', nameEn: 'Australian Dollar', flag: '🇦🇺', perUsd: 1.51 },
  { code: 'NZD', nameAr: 'دولار نيوزيلندي', nameEn: 'New Zealand Dollar', flag: '🇳🇿', perUsd: 1.71 },
  { code: 'FJD', nameAr: 'دولار فيجي', nameEn: 'Fijian Dollar', flag: '🇫🇯', perUsd: 2.27 },
  { code: 'PGK', nameAr: 'كينا بابوا', nameEn: 'Papua New Guinean Kina', flag: '🇵🇬', perUsd: 4.15 },
  { code: 'WST', nameAr: 'تالا ساموي', nameEn: 'Samoan Tala', flag: '🇼🇸', perUsd: 2.75 },
  { code: 'TOP', nameAr: 'بانغا تونغا', nameEn: 'Tongan Paʻanga', flag: '🇹🇴', perUsd: 2.38 },
  { code: 'VUV', nameAr: 'فاتو فانواتو', nameEn: 'Vanuatu Vatu', flag: '🇻🇺', perUsd: 119 },
  { code: 'SBD', nameAr: 'دولار جزر سليمان', nameEn: 'Solomon Islands Dollar', flag: '🇸🇧', perUsd: 8.45 },
  { code: 'CAD', nameAr: 'دولار كندي', nameEn: 'Canadian Dollar', flag: '🇨🇦', perUsd: 1.38 },
  { code: 'MXN', nameAr: 'بيزو مكسيكي', nameEn: 'Mexican Peso', flag: '🇲🇽', perUsd: 18.7 },
  { code: 'BRL', nameAr: 'ريال برازيلي', nameEn: 'Brazilian Real', flag: '🇧🇷', perUsd: 5.42 },
  { code: 'ARS', nameAr: 'بيزو أرجنتيني', nameEn: 'Argentine Peso', flag: '🇦🇷', perUsd: 1360 },
  { code: 'CLP', nameAr: 'بيزو تشيلي', nameEn: 'Chilean Peso', flag: '🇨🇱', perUsd: 950 },
  { code: 'COP', nameAr: 'بيزو كولومبي', nameEn: 'Colombian Peso', flag: '🇨🇴', perUsd: 4050 },
  { code: 'PEN', nameAr: 'سول بيروفي', nameEn: 'Peruvian Sol', flag: '🇵🇪', perUsd: 3.55 },
  { code: 'UYU', nameAr: 'بيزو أوروغواي', nameEn: 'Uruguayan Peso', flag: '🇺🇾', perUsd: 40.2 },
  { code: 'PYG', nameAr: 'غواراني باراغواي', nameEn: 'Paraguayan Guarani', flag: '🇵🇾', perUsd: 7900 },
  { code: 'BOB', nameAr: 'بوليفيانو', nameEn: 'Bolivian Boliviano', flag: '🇧🇴', perUsd: 6.91 },
  { code: 'VES', nameAr: 'بوليفار فنزويلي', nameEn: 'Venezuelan Bolívar', flag: '🇻🇪', perUsd: 160 },
  { code: 'GTQ', nameAr: 'كتزال غواتيمالي', nameEn: 'Guatemalan Quetzal', flag: '🇬🇹', perUsd: 7.72 },
  { code: 'HNL', nameAr: 'لمبيرة هندوراس', nameEn: 'Honduran Lempira', flag: '🇭🇳', perUsd: 26.3 },
  { code: 'NIO', nameAr: 'قرطبة نيكاراغوا', nameEn: 'Nicaraguan Córdoba', flag: '🇳🇮', perUsd: 36.8 },
  { code: 'CRC', nameAr: 'كولون كوستاريكا', nameEn: 'Costa Rican Colón', flag: '🇨🇷', perUsd: 506 },
  { code: 'PAB', nameAr: 'بالبوا بنمي', nameEn: 'Panamanian Balboa', flag: '🇵🇦', perUsd: 1 },
  { code: 'DOP', nameAr: 'بيزو دومينيكاني', nameEn: 'Dominican Peso', flag: '🇩🇴', perUsd: 62.5 },
  { code: 'CUP', nameAr: 'بيزو كوبي', nameEn: 'Cuban Peso', flag: '🇨🇺', perUsd: 24 },
  { code: 'HTG', nameAr: 'غورد هايتي', nameEn: 'Haitian Gourde', flag: '🇭🇹', perUsd: 131 },
  { code: 'JMD', nameAr: 'دولار جامايكي', nameEn: 'Jamaican Dollar', flag: '🇯🇲', perUsd: 157 },
  { code: 'TTD', nameAr: 'دولار ترينيداد', nameEn: 'Trinidad Dollar', flag: '🇹🇹', perUsd: 6.78 },
  { code: 'BBD', nameAr: 'دولار بربادوس', nameEn: 'Barbadian Dollar', flag: '🇧🇧', perUsd: 2 },
  { code: 'BSD', nameAr: 'دولار باهامي', nameEn: 'Bahamian Dollar', flag: '🇧🇸', perUsd: 1 },
  { code: 'BZD', nameAr: 'دولار بليزي', nameEn: 'Belize Dollar', flag: '🇧🇿', perUsd: 2 },
  { code: 'XCD', nameAr: 'دولار شرق الكاريبي', nameEn: 'East Caribbean Dollar', flag: '🇦🇬', perUsd: 2.7 },
  { code: 'GYD', nameAr: 'دولار غياني', nameEn: 'Guyanese Dollar', flag: '🇬🇾', perUsd: 209 },
  { code: 'SRD', nameAr: 'دولار سورينامي', nameEn: 'Surinamese Dollar', flag: '🇸🇷', perUsd: 36.5 },
  { code: 'AWG', nameAr: 'فلورن أروبي', nameEn: 'Aruban Florin', flag: '🇦🇼', perUsd: 1.8 },
  { code: 'ANG', nameAr: 'غيلدر أنتيلي', nameEn: 'Netherlands Antillean Guilder', flag: '🇨🇼', perUsd: 1.8 },
  { code: 'KYD', nameAr: 'دولار جزر كايمان', nameEn: 'Cayman Islands Dollar', flag: '🇰🇾', perUsd: 0.833 },
  { code: 'BMD', nameAr: 'دولار برمودي', nameEn: 'Bermudian Dollar', flag: '🇧🇲', perUsd: 1 },
  { code: 'CHF', nameAr: 'فرنك سويسري', nameEn: 'Swiss Franc', flag: '🇨🇭', perUsd: 0.8 },
  { code: 'NOK', nameAr: 'كرونة نرويجية', nameEn: 'Norwegian Krone', flag: '🇳🇴', perUsd: 10.05 },
  { code: 'SEK', nameAr: 'كرونة سويدية', nameEn: 'Swedish Krona', flag: '🇸🇪', perUsd: 9.42 },
  { code: 'DKK', nameAr: 'كرونة دنماركية', nameEn: 'Danish Krone', flag: '🇩🇰', perUsd: 6.42 },
  { code: 'ISK', nameAr: 'كرونة آيسلندية', nameEn: 'Icelandic Króna', flag: '🇮🇸', perUsd: 123 },
  { code: 'PLN', nameAr: 'زلوتي بولندي', nameEn: 'Polish Zloty', flag: '🇵🇱', perUsd: 3.65 },
  { code: 'CZK', nameAr: 'كرونة تشيكية', nameEn: 'Czech Koruna', flag: '🇨🇿', perUsd: 21.1 },
  { code: 'HUF', nameAr: 'فورنت مجري', nameEn: 'Hungarian Forint', flag: '🇭🇺', perUsd: 338 },
  { code: 'RON', nameAr: 'ليو روماني', nameEn: 'Romanian Leu', flag: '🇷🇴', perUsd: 4.38 },
  { code: 'BGN', nameAr: 'ليف بلغاري', nameEn: 'Bulgarian Lev', flag: '🇧🇬', perUsd: 1.68 },
  { code: 'RSD', nameAr: 'دينار صربي', nameEn: 'Serbian Dinar', flag: '🇷🇸', perUsd: 101 },
  { code: 'BAM', nameAr: 'مارك بوسني', nameEn: 'Bosnia-Herzegovina Mark', flag: '🇧🇦', perUsd: 1.68 },
  { code: 'MKD', nameAr: 'دينار مقدوني', nameEn: 'Macedonian Denar', flag: '🇲🇰', perUsd: 53 },
  { code: 'ALL', nameAr: 'ليك ألباني', nameEn: 'Albanian Lek', flag: '🇦🇱', perUsd: 83.5 },
  { code: 'MDL', nameAr: 'ليو مولدوفي', nameEn: 'Moldovan Leu', flag: '🇲🇩', perUsd: 16.9 },
  { code: 'UAH', nameAr: 'هريفنيا أوكرانية', nameEn: 'Ukrainian Hryvnia', flag: '🇺🇦', perUsd: 41.3 },
  { code: 'BYN', nameAr: 'روبل بيلاروسي', nameEn: 'Belarusian Ruble', flag: '🇧🇾', perUsd: 3.28 },
  { code: 'RUB', nameAr: 'روبل روسي', nameEn: 'Russian Ruble', flag: '🇷🇺', perUsd: 82.5 },
  { code: 'GEL', nameAr: 'لاري جورجي', nameEn: 'Georgian Lari', flag: '🇬🇪', perUsd: 2.71 },
  { code: 'AMD', nameAr: 'درام أرمني', nameEn: 'Armenian Dram', flag: '🇦🇲', perUsd: 384 },
  { code: 'AZN', nameAr: 'مانات أذربيجاني', nameEn: 'Azerbaijani Manat', flag: '🇦🇿', perUsd: 1.7 },
  { code: 'KZT', nameAr: 'تينغ كازاخستاني', nameEn: 'Kazakhstani Tenge', flag: '🇰🇿', perUsd: 538 },
  { code: 'UZS', nameAr: 'سوم أوزبكي', nameEn: 'Uzbekistani Som', flag: '🇺🇿', perUsd: 12750 },
  { code: 'TJS', nameAr: 'سوموني طاجيكي', nameEn: 'Tajikistani Somoni', flag: '🇹🇯', perUsd: 9.45 },
  { code: 'TMT', nameAr: 'مانات تركماني', nameEn: 'Turkmenistani Manat', flag: '🇹🇲', perUsd: 3.5 },
  { code: 'KGS', nameAr: 'سوم قيرغيزي', nameEn: 'Kyrgyzstani Som', flag: '🇰🇬', perUsd: 87.4 },
  { code: 'MNT', nameAr: 'توغريك منغولي', nameEn: 'Mongolian Tögrög', flag: '🇲🇳', perUsd: 3590 },
  { code: 'ZAR', nameAr: 'راند جنوب أفريقيا', nameEn: 'South African Rand', flag: '🇿🇦', perUsd: 17.6 },
  { code: 'NGN', nameAr: 'نيرة نيجيرية', nameEn: 'Nigerian Naira', flag: '🇳🇬', perUsd: 1530 },
  { code: 'GHS', nameAr: 'سيدي غاني', nameEn: 'Ghanaian Cedi', flag: '🇬🇭', perUsd: 12.1 },
  { code: 'KES', nameAr: 'شلن كيني', nameEn: 'Kenyan Shilling', flag: '🇰🇪', perUsd: 129 },
  { code: 'UGX', nameAr: 'شلن أوغندي', nameEn: 'Ugandan Shilling', flag: '🇺🇬', perUsd: 3580 },
  { code: 'TZS', nameAr: 'شلن تنزاني', nameEn: 'Tanzanian Shilling', flag: '🇹🇿', perUsd: 2470 },
  { code: 'ETB', nameAr: 'بير إثيوبي', nameEn: 'Ethiopian Birr', flag: '🇪🇹', perUsd: 143 },
  { code: 'ERN', nameAr: 'ناكفا إريترية', nameEn: 'Eritrean Nakfa', flag: '🇪🇷', perUsd: 15 },
  { code: 'SOS', nameAr: 'شلن صومالي', nameEn: 'Somali Shilling', flag: '🇸🇴', perUsd: 571 },
  { code: 'DJF', nameAr: 'فرنك جيبوتي', nameEn: 'Djiboutian Franc', flag: '🇩🇯', perUsd: 177.72 },
  { code: 'RWF', nameAr: 'فرنك رواندي', nameEn: 'Rwandan Franc', flag: '🇷🇼', perUsd: 1440 },
  { code: 'BIF', nameAr: 'فرنك بوروندي', nameEn: 'Burundian Franc', flag: '🇧🇮', perUsd: 2960 },
  { code: 'CDF', nameAr: 'فرنك كونغولي', nameEn: 'Congolese Franc', flag: '🇨🇩', perUsd: 2850 },
  { code: 'AOA', nameAr: 'كوانزا أنغولي', nameEn: 'Angolan Kwanza', flag: '🇦🇴', perUsd: 920 },
  { code: 'MZN', nameAr: 'متكال موزمبيقي', nameEn: 'Mozambican Metical', flag: '🇲🇿', perUsd: 63.8 },
  { code: 'ZMW', nameAr: 'كواشا زامبي', nameEn: 'Zambian Kwacha', flag: '🇿🇲', perUsd: 23.4 },
  { code: 'ZWG', nameAr: 'ذهب زيمبابوي', nameEn: 'Zimbabwe Gold', flag: '🇿🇼', perUsd: 26.5 },
  { code: 'MWK', nameAr: 'كواشا مالاوي', nameEn: 'Malawian Kwacha', flag: '🇲🇼', perUsd: 1735 },
  { code: 'MGA', nameAr: 'أرياري مدغشقر', nameEn: 'Malagasy Ariary', flag: '🇲🇬', perUsd: 4450 },
  { code: 'MUR', nameAr: 'روبية موريشيوس', nameEn: 'Mauritian Rupee', flag: '🇲🇺', perUsd: 45.8 },
  { code: 'SCR', nameAr: 'روبية سيشل', nameEn: 'Seychellois Rupee', flag: '🇸🇨', perUsd: 14.4 },
  { code: 'KMF', nameAr: 'فرنك جزر القمر', nameEn: 'Comorian Franc', flag: '🇰🇲', perUsd: 450 },
  { code: 'SZL', nameAr: 'ليلانغيني سوازيلند', nameEn: 'Swazi Lilangeni', flag: '🇸🇿', perUsd: 17.6 },
  { code: 'LSL', nameAr: 'لوتي ليسوتو', nameEn: 'Lesotho Loti', flag: '🇱🇸', perUsd: 17.6 },
  { code: 'NAD', nameAr: 'دولار ناميبي', nameEn: 'Namibian Dollar', flag: '🇳🇦', perUsd: 17.6 },
  { code: 'BWP', nameAr: 'بولا بوتسواني', nameEn: 'Botswana Pula', flag: '🇧🇼', perUsd: 13.5 },
  { code: 'STN', nameAr: 'دوبرا ساو تومي', nameEn: 'São Tomé Dobra', flag: '🇸🇹', perUsd: 22.6 },
  { code: 'CVE', nameAr: 'إسكودو الرأس الأخضر', nameEn: 'Cape Verdean Escudo', flag: '🇨🇻', perUsd: 94.8 },
  { code: 'GMD', nameAr: 'دلاسي غامبي', nameEn: 'Gambian Dalasi', flag: '🇬🇲', perUsd: 72.5 },
  { code: 'GNF', nameAr: 'فرنك غيني', nameEn: 'Guinean Franc', flag: '🇬🇳', perUsd: 8650 },
  { code: 'SLL', nameAr: 'ليون سيراليوني', nameEn: 'Sierra Leonean Leone', flag: '🇸🇱', perUsd: 22700 },
  { code: 'SLE', nameAr: 'ليون سيراليوني جديد', nameEn: 'Sierra Leonean Leone (new)', flag: '🇸🇱', perUsd: 22.7 },
  { code: 'LRD', nameAr: 'دولار ليبيري', nameEn: 'Liberian Dollar', flag: '🇱🇷', perUsd: 200 },
  { code: 'XOF', nameAr: 'فرنك غرب أفريقيا', nameEn: 'West African CFA Franc', flag: '🇸🇳', perUsd: 564 },
  { code: 'XAF', nameAr: 'فرنك وسط أفريقيا', nameEn: 'Central African CFA Franc', flag: '🇨🇲', perUsd: 564 },
  { code: 'XPF', nameAr: 'فرنك سي إف بي', nameEn: 'CFP Franc', flag: '🇵🇫', perUsd: 103 },
  { code: 'BTN', nameAr: 'نغولتروم بوتاني', nameEn: 'Bhutanese Ngultrum', flag: '🇧🇹', perUsd: 88.4 },
  { code: 'MOP', nameAr: 'باتاكا ماكاو', nameEn: 'Macanese Pataca', flag: '🇲🇴', perUsd: 8.01 },
  { code: 'FKP', nameAr: 'جنيه فوكلاند', nameEn: 'Falkland Islands Pound', flag: '🇫🇰', perUsd: 0.74 },
  { code: 'GIP', nameAr: 'جنيه جبل طارق', nameEn: 'Gibraltar Pound', flag: '🇬🇮', perUsd: 0.74 },
  { code: 'SHP', nameAr: 'جنيه سانت هيلينا', nameEn: 'Saint Helena Pound', flag: '🇸🇭', perUsd: 0.74 },
  { code: 'SSP', nameAr: 'جنيه جنوب السودان', nameEn: 'South Sudanese Pound', flag: '🇸🇸', perUsd: 3300 },
];

export const USD_FALLBACK_RATES: Record<string, number> = Object.fromEntries(
  WORLD_CURRENCIES.map((c) => [c.code, c.perUsd]),
);

export function convertViaUsd(amount: number, fromCode: string, toCode: string, rates: Record<string, number>) {
  const from = rates[fromCode] ?? USD_FALLBACK_RATES[fromCode] ?? 1;
  const to = rates[toCode] ?? USD_FALLBACK_RATES[toCode] ?? 1;
  if (!from || !to) return 0;
  return (amount / from) * to;
}

export function currencySearchText(c: WorldCurrency) {
  return `${c.code} ${c.nameAr} ${c.nameEn} ${c.flag}`.toLowerCase();
}
