export interface EmergencyCountry {
  iso: string;
  nameAr: string;
  nameEn: string;
  police: string;
  ambulance: string;
  fire: string;
  note?: string;
}

export const WORLD_EMERGENCY: EmergencyCountry[] = [
  { iso: 'AF', nameAr: 'أفغانستان', nameEn: 'Afghanistan', police: '119', ambulance: '112', fire: '119' },
  { iso: 'AL', nameAr: 'ألبانيا', nameEn: 'Albania', police: '112', ambulance: '127', fire: '128', note: '112 رقم أوروبي موحد' },
  { iso: 'DZ', nameAr: 'الجزائر', nameEn: 'Algeria', police: '17', ambulance: '14', fire: '14' },
  { iso: 'AD', nameAr: 'أندورا', nameEn: 'Andorra', police: '110', ambulance: '116', fire: '118' },
  { iso: 'AO', nameAr: 'أنغولا', nameEn: 'Angola', police: '113', ambulance: '112', fire: '115' },
  { iso: 'AG', nameAr: 'أنتيغوا وباربودا', nameEn: 'Antigua and Barbuda', police: '911', ambulance: '911', fire: '911' },
  { iso: 'AR', nameAr: 'الأرجنتين', nameEn: 'Argentina', police: '911', ambulance: '107', fire: '100' },
  { iso: 'AM', nameAr: 'أرمينيا', nameEn: 'Armenia', police: '102', ambulance: '103', fire: '101' },
  { iso: 'AU', nameAr: 'أستراليا', nameEn: 'Australia', police: '000', ambulance: '000', fire: '000', note: 'يمكن أيضاً طلب 112 من الجوال' },
  { iso: 'AT', nameAr: 'النمسا', nameEn: 'Austria', police: '133', ambulance: '144', fire: '122', note: '112 موحد أوروبي' },
  { iso: 'AZ', nameAr: 'أذربيجان', nameEn: 'Azerbaijan', police: '102', ambulance: '103', fire: '101' },
  { iso: 'BS', nameAr: 'الباهاما', nameEn: 'Bahamas', police: '919', ambulance: '919', fire: '919' },
  { iso: 'BH', nameAr: 'البحرين', nameEn: 'Bahrain', police: '999', ambulance: '999', fire: '998' },
  { iso: 'BD', nameAr: 'بنغلاديش', nameEn: 'Bangladesh', police: '999', ambulance: '199', fire: '199' },
  { iso: 'BB', nameAr: 'بربادوس', nameEn: 'Barbados', police: '211', ambulance: '511', fire: '311' },
  { iso: 'BY', nameAr: 'بيلاروس', nameEn: 'Belarus', police: '102', ambulance: '103', fire: '101' },
  { iso: 'BE', nameAr: 'بلجيكا', nameEn: 'Belgium', police: '101', ambulance: '112', fire: '112' },
  { iso: 'BZ', nameAr: 'بليز', nameEn: 'Belize', police: '911', ambulance: '911', fire: '911' },
  { iso: 'BJ', nameAr: 'بنين', nameEn: 'Benin', police: '117', ambulance: '112', fire: '118' },
  { iso: 'BT', nameAr: 'بوتان', nameEn: 'Bhutan', police: '113', ambulance: '112', fire: '110' },
  { iso: 'BO', nameAr: 'بوليفيا', nameEn: 'Bolivia', police: '110', ambulance: '118', fire: '119' },
  { iso: 'BA', nameAr: 'البوسنة والهرسك', nameEn: 'Bosnia and Herzegovina', police: '122', ambulance: '124', fire: '123' },
  { iso: 'BW', nameAr: 'بوتسوانا', nameEn: 'Botswana', police: '999', ambulance: '997', fire: '998' },
  { iso: 'BR', nameAr: 'البرازيل', nameEn: 'Brazil', police: '190', ambulance: '192', fire: '193' },
  { iso: 'BN', nameAr: 'بروناي', nameEn: 'Brunei', police: '993', ambulance: '991', fire: '995' },
  { iso: 'BG', nameAr: 'بلغاريا', nameEn: 'Bulgaria', police: '112', ambulance: '112', fire: '112' },
  { iso: 'BF', nameAr: 'بوركينا فاسو', nameEn: 'Burkina Faso', police: '17', ambulance: '112', fire: '18' },
  { iso: 'BI', nameAr: 'بوروندي', nameEn: 'Burundi', police: '117', ambulance: '112', fire: '118' },
  { iso: 'CV', nameAr: 'الرأس الأخضر', nameEn: 'Cabo Verde', police: '132', ambulance: '130', fire: '131' },
  { iso: 'KH', nameAr: 'كمبوديا', nameEn: 'Cambodia', police: '117', ambulance: '119', fire: '118' },
  { iso: 'CM', nameAr: 'الكاميرون', nameEn: 'Cameroon', police: '117', ambulance: '119', fire: '118' },
  { iso: 'CA', nameAr: 'كندا', nameEn: 'Canada', police: '911', ambulance: '911', fire: '911' },
  { iso: 'CF', nameAr: 'جمهورية أفريقيا الوسطى', nameEn: 'Central African Republic', police: '117', ambulance: '1220', fire: '118' },
  { iso: 'TD', nameAr: 'تشاد', nameEn: 'Chad', police: '17', ambulance: '2251-4242', fire: '18' },
  { iso: 'CL', nameAr: 'تشيلي', nameEn: 'Chile', police: '133', ambulance: '131', fire: '132' },
  { iso: 'CN', nameAr: 'الصين', nameEn: 'China', police: '110', ambulance: '120', fire: '119' },
  { iso: 'CO', nameAr: 'كولومبيا', nameEn: 'Colombia', police: '123', ambulance: '123', fire: '123' },
  { iso: 'KM', nameAr: 'جزر القمر', nameEn: 'Comoros', police: '17', ambulance: '772-03-73', fire: '18' },
  { iso: 'CG', nameAr: 'الكونغو', nameEn: 'Congo', police: '117', ambulance: '118', fire: '118' },
  { iso: 'CD', nameAr: 'الكونغو الديمقراطية', nameEn: 'DR Congo', police: '112', ambulance: '118', fire: '118' },
  { iso: 'CR', nameAr: 'كوستاريكا', nameEn: 'Costa Rica', police: '911', ambulance: '911', fire: '911' },
  { iso: 'CI', nameAr: 'ساحل العاج', nameEn: 'Côte d\'Ivoire', police: '110', ambulance: '185', fire: '180' },
  { iso: 'HR', nameAr: 'كرواتيا', nameEn: 'Croatia', police: '192', ambulance: '194', fire: '193', note: '112 موحد أوروبي' },
  { iso: 'CU', nameAr: 'كوبا', nameEn: 'Cuba', police: '106', ambulance: '104', fire: '105' },
  { iso: 'CY', nameAr: 'قبرص', nameEn: 'Cyprus', police: '112', ambulance: '112', fire: '112' },
  { iso: 'CZ', nameAr: 'التشيك', nameEn: 'Czechia', police: '158', ambulance: '155', fire: '150', note: '112 موحد أوروبي' },
  { iso: 'DK', nameAr: 'الدنمارك', nameEn: 'Denmark', police: '112', ambulance: '112', fire: '112' },
  { iso: 'DJ', nameAr: 'جيبوتي', nameEn: 'Djibouti', police: '17', ambulance: '19', fire: '18' },
  { iso: 'DM', nameAr: 'دومينيكا', nameEn: 'Dominica', police: '999', ambulance: '999', fire: '999' },
  { iso: 'DO', nameAr: 'جمهورية الدومينيكان', nameEn: 'Dominican Republic', police: '911', ambulance: '911', fire: '911' },
  { iso: 'EC', nameAr: 'الإكوادور', nameEn: 'Ecuador', police: '911', ambulance: '911', fire: '911' },
  { iso: 'EG', nameAr: 'مصر', nameEn: 'Egypt', police: '122', ambulance: '123', fire: '180' },
  { iso: 'SV', nameAr: 'السلفادور', nameEn: 'El Salvador', police: '911', ambulance: '132', fire: '913' },
  { iso: 'GQ', nameAr: 'غينيا الاستوائية', nameEn: 'Equatorial Guinea', police: '114', ambulance: '115', fire: '112' },
  { iso: 'ER', nameAr: 'إريتريا', nameEn: 'Eritrea', police: '127', ambulance: '114', fire: '116' },
  { iso: 'EE', nameAr: 'إستونيا', nameEn: 'Estonia', police: '112', ambulance: '112', fire: '112' },
  { iso: 'SZ', nameAr: 'إسواتيني', nameEn: 'Eswatini', police: '999', ambulance: '977', fire: '933' },
  { iso: 'ET', nameAr: 'إثيوبيا', nameEn: 'Ethiopia', police: '911', ambulance: '907', fire: '939' },
  { iso: 'FJ', nameAr: 'فيجي', nameEn: 'Fiji', police: '917', ambulance: '911', fire: '910' },
  { iso: 'FI', nameAr: 'فنلندا', nameEn: 'Finland', police: '112', ambulance: '112', fire: '112' },
  { iso: 'FR', nameAr: 'فرنسا', nameEn: 'France', police: '17', ambulance: '15', fire: '18', note: '112 موحد أوروبي' },
  { iso: 'GA', nameAr: 'الغابون', nameEn: 'Gabon', police: '1730', ambulance: '1300', fire: '18' },
  { iso: 'GM', nameAr: 'غامبيا', nameEn: 'Gambia', police: '117', ambulance: '116', fire: '118' },
  { iso: 'GE', nameAr: 'جورجيا', nameEn: 'Georgia', police: '112', ambulance: '112', fire: '112' },
  { iso: 'DE', nameAr: 'ألمانيا', nameEn: 'Germany', police: '110', ambulance: '112', fire: '112' },
  { iso: 'GH', nameAr: 'غانا', nameEn: 'Ghana', police: '191', ambulance: '193', fire: '192' },
  { iso: 'GR', nameAr: 'اليونان', nameEn: 'Greece', police: '100', ambulance: '166', fire: '199', note: '112 موحد أوروبي' },
  { iso: 'GD', nameAr: 'غرينادا', nameEn: 'Grenada', police: '911', ambulance: '434', fire: '112' },
  { iso: 'GT', nameAr: 'غواتيمالا', nameEn: 'Guatemala', police: '110', ambulance: '128', fire: '122' },
  { iso: 'GN', nameAr: 'غينيا', nameEn: 'Guinea', police: '117', ambulance: '442-020', fire: '18' },
  { iso: 'GW', nameAr: 'غينيا بيساو', nameEn: 'Guinea-Bissau', police: '117', ambulance: '119', fire: '118' },
  { iso: 'GY', nameAr: 'غيانا', nameEn: 'Guyana', police: '911', ambulance: '913', fire: '912' },
  { iso: 'HT', nameAr: 'هايتي', nameEn: 'Haiti', police: '114', ambulance: '116', fire: '115' },
  { iso: 'HN', nameAr: 'هندوراس', nameEn: 'Honduras', police: '911', ambulance: '195', fire: '198' },
  { iso: 'HK', nameAr: 'هونغ كونغ', nameEn: 'Hong Kong', police: '999', ambulance: '999', fire: '999' },
  { iso: 'HU', nameAr: 'المجر', nameEn: 'Hungary', police: '107', ambulance: '104', fire: '105', note: '112 موحد أوروبي' },
  { iso: 'IS', nameAr: 'آيسلندا', nameEn: 'Iceland', police: '112', ambulance: '112', fire: '112' },
  { iso: 'IN', nameAr: 'الهند', nameEn: 'India', police: '112', ambulance: '108', fire: '101' },
  { iso: 'ID', nameAr: 'إندونيسيا', nameEn: 'Indonesia', police: '110', ambulance: '118', fire: '113' },
  { iso: 'IR', nameAr: 'إيران', nameEn: 'Iran', police: '110', ambulance: '115', fire: '125' },
  { iso: 'IQ', nameAr: 'العراق', nameEn: 'Iraq', police: '104', ambulance: '122', fire: '115' },
  { iso: 'IE', nameAr: 'أيرلندا', nameEn: 'Ireland', police: '112', ambulance: '112', fire: '112', note: 'يمكن أيضاً 999' },
  { iso: 'IL', nameAr: 'إسرائيل', nameEn: 'Israel', police: '100', ambulance: '101', fire: '102' },
  { iso: 'IT', nameAr: 'إيطاليا', nameEn: 'Italy', police: '112', ambulance: '118', fire: '115' },
  { iso: 'JM', nameAr: 'جامايكا', nameEn: 'Jamaica', police: '119', ambulance: '110', fire: '110' },
  { iso: 'JP', nameAr: 'اليابان', nameEn: 'Japan', police: '110', ambulance: '119', fire: '119' },
  { iso: 'JO', nameAr: 'الأردن', nameEn: 'Jordan', police: '911', ambulance: '911', fire: '911' },
  { iso: 'KZ', nameAr: 'كازاخستان', nameEn: 'Kazakhstan', police: '102', ambulance: '103', fire: '101' },
  { iso: 'KE', nameAr: 'كينيا', nameEn: 'Kenya', police: '999', ambulance: '999', fire: '999', note: 'يمكن أيضاً 112' },
  { iso: 'KI', nameAr: 'كيريباتي', nameEn: 'Kiribati', police: '992', ambulance: '994', fire: '993' },
  { iso: 'KW', nameAr: 'الكويت', nameEn: 'Kuwait', police: '112', ambulance: '112', fire: '112' },
  { iso: 'KG', nameAr: 'قيرغيزستان', nameEn: 'Kyrgyzstan', police: '102', ambulance: '103', fire: '101' },
  { iso: 'LA', nameAr: 'لاوس', nameEn: 'Laos', police: '191', ambulance: '195', fire: '190' },
  { iso: 'LV', nameAr: 'لاتفيا', nameEn: 'Latvia', police: '110', ambulance: '113', fire: '112' },
  { iso: 'LB', nameAr: 'لبنان', nameEn: 'Lebanon', police: '112', ambulance: '140', fire: '175' },
  { iso: 'LS', nameAr: 'ليسوتو', nameEn: 'Lesotho', police: '123', ambulance: '121', fire: '122' },
  { iso: 'LR', nameAr: 'ليبيريا', nameEn: 'Liberia', police: '911', ambulance: '911', fire: '911' },
  { iso: 'LY', nameAr: 'ليبيا', nameEn: 'Libya', police: '193', ambulance: '1515', fire: '1515' },
  { iso: 'LI', nameAr: 'ليختنشتاين', nameEn: 'Liechtenstein', police: '117', ambulance: '144', fire: '118' },
  { iso: 'LT', nameAr: 'ليتوانيا', nameEn: 'Lithuania', police: '112', ambulance: '112', fire: '112' },
  { iso: 'LU', nameAr: 'لوكسمبورغ', nameEn: 'Luxembourg', police: '113', ambulance: '112', fire: '112' },
  { iso: 'MO', nameAr: 'ماكاو', nameEn: 'Macau', police: '999', ambulance: '999', fire: '999' },
  { iso: 'MG', nameAr: 'مدغشقر', nameEn: 'Madagascar', police: '117', ambulance: '124', fire: '118' },
  { iso: 'MW', nameAr: 'مالاوي', nameEn: 'Malawi', police: '997', ambulance: '998', fire: '999' },
  { iso: 'MY', nameAr: 'ماليزيا', nameEn: 'Malaysia', police: '999', ambulance: '999', fire: '994' },
  { iso: 'MV', nameAr: 'المالديف', nameEn: 'Maldives', police: '119', ambulance: '102', fire: '118' },
  { iso: 'ML', nameAr: 'مالي', nameEn: 'Mali', police: '17', ambulance: '15', fire: '18' },
  { iso: 'MT', nameAr: 'مالطا', nameEn: 'Malta', police: '112', ambulance: '112', fire: '112' },
  { iso: 'MH', nameAr: 'جزر مارشال', nameEn: 'Marshall Islands', police: '911', ambulance: '911', fire: '911' },
  { iso: 'MR', nameAr: 'موريتانيا', nameEn: 'Mauritania', police: '117', ambulance: '101', fire: '118' },
  { iso: 'MU', nameAr: 'موريشيوس', nameEn: 'Mauritius', police: '999', ambulance: '114', fire: '115' },
  { iso: 'MX', nameAr: 'المكسيك', nameEn: 'Mexico', police: '911', ambulance: '911', fire: '911' },
  { iso: 'FM', nameAr: 'ميكرونيزيا', nameEn: 'Micronesia', police: '911', ambulance: '911', fire: '911' },
  { iso: 'MD', nameAr: 'مولدوفا', nameEn: 'Moldova', police: '112', ambulance: '903', fire: '901' },
  { iso: 'MC', nameAr: 'موناكو', nameEn: 'Monaco', police: '17', ambulance: '18', fire: '18' },
  { iso: 'MN', nameAr: 'منغوليا', nameEn: 'Mongolia', police: '102', ambulance: '103', fire: '101' },
  { iso: 'ME', nameAr: 'الجبل الأسود', nameEn: 'Montenegro', police: '122', ambulance: '124', fire: '123' },
  { iso: 'MA', nameAr: 'المغرب', nameEn: 'Morocco', police: '19', ambulance: '15', fire: '15' },
  { iso: 'MZ', nameAr: 'موزمبيق', nameEn: 'Mozambique', police: '119', ambulance: '117', fire: '198' },
  { iso: 'MM', nameAr: 'ميانمار', nameEn: 'Myanmar', police: '199', ambulance: '192', fire: '191' },
  { iso: 'NA', nameAr: 'ناميبيا', nameEn: 'Namibia', police: '10111', ambulance: '211111', fire: '2032270' },
  { iso: 'NR', nameAr: 'ناورو', nameEn: 'Nauru', police: '110', ambulance: '111', fire: '112' },
  { iso: 'NP', nameAr: 'نيبال', nameEn: 'Nepal', police: '100', ambulance: '102', fire: '101' },
  { iso: 'NL', nameAr: 'هولندا', nameEn: 'Netherlands', police: '112', ambulance: '112', fire: '112' },
  { iso: 'NZ', nameAr: 'نيوزيلندا', nameEn: 'New Zealand', police: '111', ambulance: '111', fire: '111' },
  { iso: 'NI', nameAr: 'نيكاراغوا', nameEn: 'Nicaragua', police: '118', ambulance: '128', fire: '115' },
  { iso: 'NE', nameAr: 'النيجر', nameEn: 'Niger', police: '17', ambulance: '15', fire: '18' },
  { iso: 'NG', nameAr: 'نيجيريا', nameEn: 'Nigeria', police: '112', ambulance: '112', fire: '112' },
  { iso: 'KP', nameAr: 'كوريا الشمالية', nameEn: 'North Korea', police: '119', ambulance: '119', fire: '119' },
  { iso: 'MK', nameAr: 'مقدونيا الشمالية', nameEn: 'North Macedonia', police: '192', ambulance: '194', fire: '193' },
  { iso: 'NO', nameAr: 'النرويج', nameEn: 'Norway', police: '112', ambulance: '113', fire: '110' },
  { iso: 'OM', nameAr: 'عُمان', nameEn: 'Oman', police: '9999', ambulance: '9999', fire: '9999' },
  { iso: 'PK', nameAr: 'باكستان', nameEn: 'Pakistan', police: '15', ambulance: '115', fire: '16' },
  { iso: 'PW', nameAr: 'بالاو', nameEn: 'Palau', police: '911', ambulance: '911', fire: '911' },
  { iso: 'PS', nameAr: 'فلسطين', nameEn: 'Palestine', police: '100', ambulance: '101', fire: '102' },
  { iso: 'PA', nameAr: 'بنما', nameEn: 'Panama', police: '911', ambulance: '911', fire: '911' },
  { iso: 'PG', nameAr: 'بابوا غينيا الجديدة', nameEn: 'Papua New Guinea', police: '000', ambulance: '111', fire: '110' },
  { iso: 'PY', nameAr: 'باراغواي', nameEn: 'Paraguay', police: '911', ambulance: '141', fire: '132' },
  { iso: 'PE', nameAr: 'بيرو', nameEn: 'Peru', police: '105', ambulance: '106', fire: '116' },
  { iso: 'PH', nameAr: 'الفلبين', nameEn: 'Philippines', police: '911', ambulance: '911', fire: '911' },
  { iso: 'PL', nameAr: 'بولندا', nameEn: 'Poland', police: '997', ambulance: '999', fire: '998', note: '112 موحد أوروبي' },
  { iso: 'PT', nameAr: 'البرتغال', nameEn: 'Portugal', police: '112', ambulance: '112', fire: '112' },
  { iso: 'QA', nameAr: 'قطر', nameEn: 'Qatar', police: '999', ambulance: '999', fire: '999' },
  { iso: 'RO', nameAr: 'رومانيا', nameEn: 'Romania', police: '112', ambulance: '112', fire: '112' },
  { iso: 'RU', nameAr: 'روسيا', nameEn: 'Russia', police: '102', ambulance: '103', fire: '101' },
  { iso: 'RW', nameAr: 'رواندا', nameEn: 'Rwanda', police: '112', ambulance: '912', fire: '111' },
  { iso: 'KN', nameAr: 'سانت كيتس ونيفيس', nameEn: 'Saint Kitts and Nevis', police: '911', ambulance: '911', fire: '911' },
  { iso: 'LC', nameAr: 'سانت لوسيا', nameEn: 'Saint Lucia', police: '999', ambulance: '911', fire: '911' },
  { iso: 'VC', nameAr: 'سانت فنسنت', nameEn: 'Saint Vincent and the Grenadines', police: '999', ambulance: '999', fire: '999' },
  { iso: 'WS', nameAr: 'ساموا', nameEn: 'Samoa', police: '995', ambulance: '994', fire: '996' },
  { iso: 'SM', nameAr: 'سان مارينو', nameEn: 'San Marino', police: '112', ambulance: '118', fire: '115' },
  { iso: 'ST', nameAr: 'ساو تومي وبرينسيبي', nameEn: 'Sao Tome and Principe', police: '112', ambulance: '112', fire: '112' },
  { iso: 'SA', nameAr: 'السعودية', nameEn: 'Saudi Arabia', police: '999', ambulance: '997', fire: '998' },
  { iso: 'SN', nameAr: 'السنغال', nameEn: 'Senegal', police: '17', ambulance: '15', fire: '18' },
  { iso: 'RS', nameAr: 'صربيا', nameEn: 'Serbia', police: '192', ambulance: '194', fire: '193' },
  { iso: 'SC', nameAr: 'سيشل', nameEn: 'Seychelles', police: '999', ambulance: '151', fire: '999' },
  { iso: 'SL', nameAr: 'سيراليون', nameEn: 'Sierra Leone', police: '019', ambulance: '999', fire: '999' },
  { iso: 'SG', nameAr: 'سنغافورة', nameEn: 'Singapore', police: '999', ambulance: '995', fire: '995' },
  { iso: 'SK', nameAr: 'سلوفاكيا', nameEn: 'Slovakia', police: '158', ambulance: '155', fire: '150', note: '112 موحد أوروبي' },
  { iso: 'SI', nameAr: 'سلوفينيا', nameEn: 'Slovenia', police: '113', ambulance: '112', fire: '112' },
  { iso: 'SB', nameAr: 'جزر سليمان', nameEn: 'Solomon Islands', police: '999', ambulance: '911', fire: '988' },
  { iso: 'SO', nameAr: 'الصومال', nameEn: 'Somalia', police: '888', ambulance: '555', fire: '777' },
  { iso: 'ZA', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa', police: '10111', ambulance: '10177', fire: '10177' },
  { iso: 'KR', nameAr: 'كوريا الجنوبية', nameEn: 'South Korea', police: '112', ambulance: '119', fire: '119' },
  { iso: 'SS', nameAr: 'جنوب السودان', nameEn: 'South Sudan', police: '999', ambulance: '999', fire: '999' },
  { iso: 'ES', nameAr: 'إسبانيا', nameEn: 'Spain', police: '112', ambulance: '112', fire: '112' },
  { iso: 'LK', nameAr: 'سريلانكا', nameEn: 'Sri Lanka', police: '119', ambulance: '1990', fire: '110' },
  { iso: 'SD', nameAr: 'السودان', nameEn: 'Sudan', police: '999', ambulance: '333', fire: '777' },
  { iso: 'SR', nameAr: 'سورينام', nameEn: 'Suriname', police: '115', ambulance: '113', fire: '110' },
  { iso: 'SE', nameAr: 'السويد', nameEn: 'Sweden', police: '112', ambulance: '112', fire: '112' },
  { iso: 'CH', nameAr: 'سويسرا', nameEn: 'Switzerland', police: '117', ambulance: '144', fire: '118' },
  { iso: 'SY', nameAr: 'سوريا', nameEn: 'Syria', police: '112', ambulance: '110', fire: '113' },
  { iso: 'TW', nameAr: 'تايوان', nameEn: 'Taiwan', police: '110', ambulance: '119', fire: '119' },
  { iso: 'TJ', nameAr: 'طاجيكستان', nameEn: 'Tajikistan', police: '102', ambulance: '103', fire: '101' },
  { iso: 'TZ', nameAr: 'تنزانيا', nameEn: 'Tanzania', police: '112', ambulance: '114', fire: '115' },
  { iso: 'TH', nameAr: 'تايلاند', nameEn: 'Thailand', police: '191', ambulance: '1669', fire: '199' },
  { iso: 'TL', nameAr: 'تيمور الشرقية', nameEn: 'Timor-Leste', police: '112', ambulance: '110', fire: '115' },
  { iso: 'TG', nameAr: 'توغو', nameEn: 'Togo', police: '117', ambulance: '8200', fire: '118' },
  { iso: 'TO', nameAr: 'تونغا', nameEn: 'Tonga', police: '911', ambulance: '911', fire: '911' },
  { iso: 'TT', nameAr: 'ترينيداد وتوباغو', nameEn: 'Trinidad and Tobago', police: '999', ambulance: '811', fire: '990' },
  { iso: 'TN', nameAr: 'تونس', nameEn: 'Tunisia', police: '197', ambulance: '190', fire: '198' },
  { iso: 'TR', nameAr: 'تركيا', nameEn: 'Turkey', police: '112', ambulance: '112', fire: '112', note: 'تركيا تعتمد الرقم الموحد 112 للشرطة والإسعاف والإطفاء' },
  { iso: 'TM', nameAr: 'تركمانستان', nameEn: 'Turkmenistan', police: '102', ambulance: '103', fire: '101' },
  { iso: 'TV', nameAr: 'توفالو', nameEn: 'Tuvalu', police: '911', ambulance: '911', fire: '911' },
  { iso: 'UG', nameAr: 'أوغندا', nameEn: 'Uganda', police: '112', ambulance: '911', fire: '999' },
  { iso: 'UA', nameAr: 'أوكرانيا', nameEn: 'Ukraine', police: '102', ambulance: '103', fire: '101' },
  { iso: 'AE', nameAr: 'الإمارات', nameEn: 'United Arab Emirates', police: '999', ambulance: '998', fire: '997' },
  { iso: 'GB', nameAr: 'المملكة المتحدة', nameEn: 'United Kingdom', police: '999', ambulance: '999', fire: '999', note: 'يمكن أيضاً 112' },
  { iso: 'US', nameAr: 'الولايات المتحدة', nameEn: 'United States', police: '911', ambulance: '911', fire: '911' },
  { iso: 'UY', nameAr: 'الأوروغواي', nameEn: 'Uruguay', police: '911', ambulance: '911', fire: '911' },
  { iso: 'UZ', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan', police: '102', ambulance: '103', fire: '101' },
  { iso: 'VU', nameAr: 'فانواتو', nameEn: 'Vanuatu', police: '111', ambulance: '112', fire: '113' },
  { iso: 'VA', nameAr: 'الفاتيكان', nameEn: 'Vatican City', police: '112', ambulance: '118', fire: '115' },
  { iso: 'VE', nameAr: 'فنزويلا', nameEn: 'Venezuela', police: '911', ambulance: '911', fire: '911' },
  { iso: 'VN', nameAr: 'فيتنام', nameEn: 'Vietnam', police: '113', ambulance: '115', fire: '114' },
  { iso: 'YE', nameAr: 'اليمن', nameEn: 'Yemen', police: '199', ambulance: '191', fire: '191' },
  { iso: 'ZM', nameAr: 'زامبيا', nameEn: 'Zambia', police: '999', ambulance: '992', fire: '993' },
  { iso: 'ZW', nameAr: 'زيمبابوي', nameEn: 'Zimbabwe', police: '999', ambulance: '994', fire: '993' },
  { iso: 'XK', nameAr: 'كوسوفو', nameEn: 'Kosovo', police: '192', ambulance: '194', fire: '193' },
];

export function emergencySearchText(c: EmergencyCountry) {
  return `${c.iso} ${c.nameAr} ${c.nameEn}`.toLowerCase();
}

export function findEmergencyCountry(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return undefined;
  return WORLD_EMERGENCY.find(
    (c) =>
      c.nameAr === query ||
      c.nameEn.toLowerCase() === q ||
      c.iso.toLowerCase() === q ||
      c.nameAr.includes(query) ||
      c.nameEn.toLowerCase().includes(q),
  );
}
